### ISSUE TITLE
Add option to reformat all changed files

### ISSUE THREAD

**Issue by jrepe** [ragurney/spotless-intellij-gradle#46]
Currently, only the currently selected file can be formatted, which is cumbersome if you have a lot of files. Would it be possible to add an option to format all files that were changed?

Btw, if this is something you think would be a good addition, I can also have a go at contributing this myself.

Kind regards

**Comment by ragurney** [comment]
Hi @jrepe, thanks for opening this issue. I'd be happy to accept a PR for this if you're interested in contributing! 

I think the high level this would entail:
- Adding a new action similar to [this one](https://github.com/ragurney/spotless-intellij-gradle/blob/main/src/main/java/com/github/ragurney/spotless/actions/ReformatCodeAction.java) and registering it [here](https://github.com/ragurney/spotless-intellij-gradle/blob/main/src/main/resources/META-INF/plugin.xml#L15).
- Passing a flag from the new action that could remove this flag [here](https://github.com/ragurney/spotless-intellij-gradle/blob/main/src/main/java/com/github/ragurney/spotless/actions/ReformatCodeProcessor.java#L108).

**Comment by jrepe** [comment]
Alright, thanks for the quick response. I can have a go at this as soon as I find some time 👍🏻

**Comment by ragurney** [comment]
Ok sounds good, thanks so much! ❤️  If at any time you'd rather me do if you don't have the time let me know, but it'd be great to have others contributing.
